2023-06-29 20:55:27,318	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 20:55:27,737	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 20:55:27,738	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 20:55:27,738	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 20:55:27,738	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 20:55:27,863	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 20:55:27,966	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 20:55:27,966	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 20:55:27,967	[INFO]	(测试.py:17)on_ready	robot 「test-测试中」 on_ready!
2023-06-29 20:56:11,283	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 20:56:11,735	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 20:56:11,735	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 20:56:11,735	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 20:56:11,735	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 20:56:11,849	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 20:56:11,968	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 20:56:11,968	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 20:56:11,969	[INFO]	(测试.py:17)on_ready	robot 「test-测试中」 on_ready!
2023-06-29 20:56:30,053	[INFO]	(测试.py:20)on_at_message_create	https://qqchannel-profile-1251316161.file.myqcloud.com/16605616176d9cc4db9e8eebcd?t=1660561617
2023-06-29 20:56:30,053	[INFO]	(测试.py:23)on_at_message_create	白瞎子
2023-06-29 20:57:33,405	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 20:57:33,537	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/users/@me, 错误代码: 401, 返回内容: {'message': 'check bot token not pass', 'code': 11243}, trace_id:4a9d20b569c24ab1c51c949f1be4460b
2023-06-29 23:06:23,574	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:06:23,977	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:06:23,977	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:06:23,978	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:06:23,978	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:06:24,126	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:06:24,255	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:06:24,256	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:06:39,448	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/xxxx/mute, 错误代码: 502, 返回内容: {'message': 'replace query param error', 'code': 11300}, trace_id:16d4ce2873609de8fc4a3dc41eec1a80
2023-06-29 23:07:43,184	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:07:43,615	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:07:43,615	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:07:43,615	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:07:43,615	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:07:43,735	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:07:43,840	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:07:43,841	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:10:35,146	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:10:35,552	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:10:35,552	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:10:35,552	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:10:35,552	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:10:35,688	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:10:35,782	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:10:35,783	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:11:05,964	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/xxxx/members/xxx, 错误代码: 502, 返回内容: {'message': 'replace query param error', 'code': 11300}, trace_id:27d6ed95c5e3d5182101a4d8c2fd7677
2023-06-29 23:12:35,582	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:12:36,007	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:12:36,007	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:12:36,008	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:12:36,008	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:12:36,119	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:12:36,190	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:12:36,190	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:12:42,370	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/13346486689812486705/members/08b1b4828ee8dd8f9cb90110818afa8a02384248e9bef6a406, 错误代码: 502, 返回内容: {'message': 'replace query param error', 'code': 11300}, trace_id:ea23eeefe9e8eef7896c15c850a71597
2023-06-29 23:14:15,335	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:14:15,765	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:14:15,765	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:14:15,766	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:14:15,766	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:14:15,889	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:14:15,970	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:14:15,970	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:14:54,172	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/13346486689812486705/members/%7B'id':%20'9282202926517215240',%20'username':%20'%E6%B0%A7%E5%8C%96%E6%88%90%E7%A1%AB',%20'bot':%20False,%20'avatar':%20'http://thirdqq.qlogo.cn/g?b=oidb&k=SZO8VIpuDNNvDpt8y43hzA&kti=ZJ1iMQAAAAA&s=0&t=1676469450'%7D, 错误代码: 404, 返回内容: {'message': '404: Not Found', 'code': 0}, trace_id:c7af3ee7c7003e341666df67173cfdcd
2023-06-29 23:22:45,252	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:22:45,652	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:22:45,652	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:22:45,652	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:22:45,652	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:22:45,799	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:22:45,936	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:22:45,936	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:23:18,030	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:23:18,453	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:23:18,453	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:23:18,453	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:23:18,454	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:23:18,668	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:23:18,748	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:23:18,748	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:24:27,549	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:24:27,954	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:24:27,955	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:24:27,955	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:24:27,955	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:24:28,072	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:24:28,148	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:24:28,148	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:25:18,005	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:25:18,414	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:25:18,414	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:25:18,415	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:25:18,415	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:25:18,527	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:25:18,591	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:25:18,592	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:25:53,660	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:25:54,051	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:25:54,051	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:25:54,051	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:25:54,052	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:25:54,166	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:25:54,219	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:25:54,219	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:26:41,029	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:26:41,421	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:26:41,421	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:26:41,422	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:26:41,422	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:26:41,552	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:26:41,624	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:26:41,624	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:27:24,091	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:27:24,477	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:27:24,478	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:27:24,478	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:27:24,478	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:27:24,595	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:27:24,661	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:27:24,662	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:28:54,396	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:28:54,807	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:28:54,807	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:28:54,808	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:28:54,808	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:28:54,938	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:28:55,010	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:28:55,010	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:30:20,693	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:30:21,073	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:30:21,073	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:30:21,073	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:30:21,073	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:30:21,186	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:30:21,242	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:30:21,242	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:33:11,102	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:33:11,523	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:33:11,523	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:33:11,523	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:33:11,523	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:33:11,651	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:33:11,773	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:33:11,774	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:33:35,095	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:fe1f83b0789916db06fd91d854a70b59
2023-06-29 23:34:20,566	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:34:20,981	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:34:20,981	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:34:20,981	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:34:20,981	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:34:21,106	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:34:21,204	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:34:21,204	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:34:34,422	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:fae5347cd7d4f02ff96b48809fc6a3d0
2023-06-29 23:34:57,484	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:86f446d821ca71ffa9a83123ce972aa7
2023-06-29 23:35:57,895	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:35:58,269	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:35:58,269	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:35:58,269	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:35:58,269	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:35:58,408	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:35:58,536	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:35:58,536	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:36:34,934	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:36:35,330	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:36:35,330	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:36:35,331	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:36:35,331	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:36:35,487	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:36:35,578	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:36:35,578	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:36:52,276	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:36:52,664	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:36:52,664	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:36:52,665	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:36:52,665	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:36:52,789	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:36:52,859	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:36:52,859	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:37:36,294	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:37:36,662	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:37:36,663	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:37:36,663	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:37:36,663	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:37:36,813	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:37:36,894	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:37:36,894	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:38:34,347	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:38:34,726	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:38:34,726	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:38:34,726	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:38:34,726	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:38:34,841	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:38:34,897	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:38:34,898	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:38:45,388	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:38:45,764	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:38:45,764	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:38:45,764	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:38:45,765	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:38:45,900	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:38:45,982	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:38:45,982	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:38:58,206	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:7b09c3a5f9cb304f58b48b40e6d5c2d9
2023-06-29 23:39:05,485	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:39:05,853	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:39:05,853	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:39:05,853	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:39:05,853	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:39:05,993	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:39:06,066	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:39:06,066	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:40:13,879	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:40:14,330	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:40:14,331	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:40:14,331	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:40:14,331	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:40:14,446	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:40:14,529	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:40:14,529	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:40:20,728	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:da25c08f5d0e68c6feaed3b23bb7ccd6
2023-06-29 23:46:57,334	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:46:57,816	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:46:57,817	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:46:57,817	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:46:57,817	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:46:57,947	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:46:58,029	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:46:58,029	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:47:06,245	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:88082da2fda627d9a553a7b2523c318a
2023-06-29 23:47:19,384	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:47:19,736	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:47:19,736	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:47:19,736	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:47:19,737	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:47:19,870	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:47:19,924	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:47:19,924	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:47:33,173	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:47b56963978c859f59f51f1c23672cd2
2023-06-29 23:47:40,486	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:47:40,857	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:47:40,857	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:47:40,857	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:47:40,857	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:47:41,007	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:47:41,141	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:47:41,141	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:49:38,211	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:49:38,612	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:49:38,613	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:49:38,613	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:49:38,613	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:49:38,761	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:49:38,859	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-29 23:49:38,859	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:50:23,907	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:50:24,418	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:50:24,418	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:50:24,418	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:50:24,418	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:50:24,546	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:50:24,613	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:50:24,613	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:51:10,220	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:51:10,609	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:51:10,610	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:51:10,610	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:51:10,610	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:51:10,734	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:51:10,796	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:51:10,796	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:51:31,573	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:51:32,023	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:51:32,023	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:51:32,023	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:51:32,023	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:51:32,167	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:51:32,285	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:51:32,285	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:52:10,133	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:52:10,496	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:52:10,496	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:52:10,497	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:52:10,497	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:52:10,645	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:52:10,717	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:52:10,717	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:53:31,786	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:53:32,227	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:53:32,227	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:53:32,227	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:53:32,227	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:53:32,377	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:53:32,480	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:53:32,480	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:54:09,900	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:54:10,270	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:54:10,270	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:54:10,271	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:54:10,271	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:54:10,408	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:54:10,481	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:54:10,481	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:54:48,946	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:54:49,343	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:54:49,344	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:54:49,344	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:54:49,345	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:54:49,464	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:54:49,561	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:54:49,561	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:55:29,729	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:55:30,118	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:55:30,119	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:55:30,119	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:55:30,119	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:55:30,261	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:55:30,334	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:55:30,334	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:57:58,918	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:57:59,327	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:57:59,327	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:57:59,328	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:57:59,328	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:57:59,442	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:57:59,570	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:57:59,570	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:58:27,907	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:8398d7102af4fc71f936e64b0fc3e5df
2023-06-29 23:59:19,332	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-29 23:59:19,765	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-29 23:59:19,765	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-29 23:59:19,766	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-29 23:59:19,766	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-29 23:59:19,911	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-29 23:59:20,015	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-29 23:59:20,015	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-29 23:59:27,248	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:3d6d4403e2d50c2a9a2ad50778e75427
2023-06-29 23:59:59,916	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:00:00,305	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:00:00,306	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:00:00,306	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:00:00,306	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:00:00,441	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:00:00,536	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:00:00,536	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:02:01,291	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:02:06,329	[WARNING]	(http.py:188)request	请求超时，请求连接: https://api.sgroup.qq.com/users/@me
2023-06-30 00:02:11,330	[WARNING]	(http.py:188)request	请求超时，请求连接: https://api.sgroup.qq.com/gateway/bot
2023-06-30 00:05:39,042	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:05:39,996	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:05:39,996	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:05:39,996	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:05:39,996	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:05:40,362	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:05:40,509	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:05:40,510	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:05:58,008	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:e4b74beff266dfdee498b161ed5f2411
2023-06-30 00:05:58,536	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559706124/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:03a4ed872fb3c92b89363bc87d41b272
2023-06-30 00:06:55,733	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:06:56,769	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:06:56,769	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:06:56,770	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:06:56,770	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:06:57,133	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:06:57,246	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:06:57,248	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:07:23,738	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:68f914b8c871fc48c43d3d4c40c83a28
2023-06-30 00:07:24,294	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559706124/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:a2d1d4d884ae6ece68f062c6d82d5df3
2023-06-30 00:07:39,730	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:07:40,589	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:07:40,590	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:07:40,590	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:07:40,590	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:07:40,993	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:07:41,161	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:07:41,162	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:07:48,313	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559706124/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:33cf4db49f1927d8bf0360ce16924228
2023-06-30 00:08:18,084	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:08:19,064	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:08:19,064	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:08:19,064	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:08:19,064	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:08:19,452	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:08:19,574	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:08:19,574	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:08:31,833	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:13c9aff2939d5198785dff381d589a82
2023-06-30 00:09:16,502	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:09:17,632	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:09:17,632	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:09:17,632	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:09:17,633	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:09:18,008	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:09:18,178	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:09:18,179	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:09:36,544	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:97759dc515a69b9ac3bb30583d8c61aa
2023-06-30 00:12:30,859	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:12:31,967	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:12:31,968	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:12:31,968	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:12:31,968	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:12:32,391	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:12:32,544	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:12:32,545	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:12:50,209	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:7e7810a27c5b9acfd30d5878319ea2a8
2023-06-30 00:21:59,494	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:22:00,431	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:22:00,431	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:22:00,433	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:22:00,433	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:22:00,855	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:22:00,970	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:22:00,970	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:22:22,099	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:2b5c03a463a2136be37f026692934001
2023-06-30 00:22:22,410	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:ed496aa330c3d962efc8371d3d7d9116
2023-06-30 00:22:38,311	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:22:39,332	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:22:39,332	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:22:39,333	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:22:39,333	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:22:39,773	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:22:39,959	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:22:39,959	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:22:48,066	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:9c3bfc23cde1eec474dfffcb09dcadb1
2023-06-30 00:22:49,359	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:8c9198335fd33167e8a65dd0470f5faa
2023-06-30 00:23:08,302	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:23:09,142	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:23:09,144	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:23:09,144	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:23:09,144	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:23:09,605	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:23:09,744	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:23:09,744	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:23:09,745	[INFO]	(测试.py:17)on_ready	robot 「test-测试中」 on_ready!
2023-06-30 00:23:17,779	[INFO]	(测试.py:20)on_at_message_create	https://qqchannel-profile-1251316161.file.myqcloud.com/16605616176d9cc4db9e8eebcd?t=1660561617
2023-06-30 00:23:17,780	[INFO]	(测试.py:23)on_at_message_create	白瞎子
2023-06-30 00:23:18,521	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:203c31aab5c3b71b790382f5eb487eb3
2023-06-30 00:23:19,353	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:d19b9b17f536e86e1afcadaa4592b9d6
2023-06-30 00:23:36,853	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:23:37,650	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:23:37,651	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:23:37,651	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:23:37,651	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:23:38,014	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:23:38,182	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:23:38,182	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:23:46,851	[INFO]	(测试.py:20)on_at_message_create	https://qqchannel-profile-1251316161.file.myqcloud.com/16605616176d9cc4db9e8eebcd?t=1660561617
2023-06-30 00:23:46,851	[INFO]	(测试.py:23)on_at_message_create	白瞎子
2023-06-30 00:23:47,617	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:ac29c0fc4af3c1f2705d3128f309b62b
2023-06-30 00:23:48,288	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:46d3b3241fb745591e9522a0abb4eb5d
2023-06-30 00:29:02,639	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:29:03,669	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:29:03,669	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:29:03,669	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:29:03,669	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:29:04,059	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:29:04,240	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:29:04,240	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:29:25,353	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:0aed06b7cdc72773c6a7a6b0e0baa523
2023-06-30 00:29:25,979	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:0a7260e7abe5378d5c7b382213d1af8b
2023-06-30 00:29:55,214	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:29:56,200	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:29:56,200	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:29:56,200	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:29:56,200	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:29:56,574	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:29:56,705	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:29:56,706	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:30:10,063	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:6added8fd68ffb89dafe205300e00752
2023-06-30 00:30:10,113	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:26a8cce3dd862c983fee592a5a94dd23
2023-06-30 00:30:32,255	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:30:33,183	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:30:33,183	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:30:33,183	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:30:33,183	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:30:33,553	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:30:33,691	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:30:33,692	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:30:42,319	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:7823e42b64b55b88f8a4d956e55adec7
2023-06-30 00:30:58,277	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:30:59,277	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:30:59,277	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:30:59,278	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:30:59,278	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:30:59,680	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:30:59,828	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:30:59,828	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:31:07,361	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:7f2c5f20f06bdc5b1106dbab77c48345
2023-06-30 00:31:08,040	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:987157d0710aa5c5f24b30f2a21d2875
2023-06-30 00:31:30,279	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:31:31,273	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:31:31,273	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:31:31,273	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:31:31,274	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:31:31,702	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:31:31,838	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:31:31,838	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:31:40,593	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:ed617df6fcdc15c8f367840b1bd350a5
2023-06-30 00:31:40,950	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:30801ecbbe891a4d6f484267cbe147c6
2023-06-30 00:32:51,635	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:32:52,722	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:32:52,722	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:32:52,722	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:32:52,722	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:32:53,196	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:32:53,432	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:32:53,432	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:33:05,864	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:a69255dadbed1e0033b9f085fefbfcfa
2023-06-30 00:33:06,237	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:2c325c8990a9282036b555a7477e9458
2023-06-30 00:34:08,757	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:34:09,894	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:34:09,894	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:34:09,894	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:34:09,894	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:34:10,435	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:34:10,643	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:34:10,644	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:34:19,323	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:6cde45c8357eb3a97469e616d1fe8a58
2023-06-30 00:34:30,905	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:34:31,912	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:34:31,912	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:34:31,912	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:34:31,912	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:34:32,407	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:34:32,549	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:34:32,549	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:34:39,815	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:7e29c34aeed41c62daf98e3a106a8e99
2023-06-30 00:34:40,245	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:13faac66f5acfa831be5f2865b96be0a
2023-06-30 00:34:50,127	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:34:51,257	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:34:51,257	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:34:51,257	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:34:51,257	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:34:51,774	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:34:51,911	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:34:51,911	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:35:02,199	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:202c90e41369815c50db16c6f3c263c2
2023-06-30 00:35:02,770	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:78debc90e5ce86ae447e17efbe30ab5a
2023-06-30 00:36:52,272	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:36:53,175	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:36:53,176	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:36:53,176	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:36:53,176	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:36:53,591	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:36:53,735	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:36:53,735	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:37:09,049	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:240934c0a93c51d88c6698de30b2677c
2023-06-30 00:40:07,744	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:40:08,752	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:40:08,752	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:40:08,752	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:40:08,752	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:40:09,104	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:40:09,222	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:40:09,222	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:40:22,372	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:224c885f2572f19599e9c4d86084d30f
2023-06-30 00:41:52,996	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:41:54,018	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:41:54,019	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:41:54,019	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:41:54,019	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:41:54,452	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:41:54,621	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:41:54,621	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:42:03,757	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:42:04,767	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:42:04,767	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:42:04,768	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:42:04,768	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:42:05,222	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:42:05,443	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:42:05,443	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:42:15,755	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:03cd79e169d0b02ff31d16d22cfa56f2
2023-06-30 00:42:32,430	[INFO]	(gateway.py:54)on_closed	[botpy] 关闭, 返回码: 4009, 返回信息: Session timed out
2023-06-30 00:42:33,678	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:42:34,706	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:42:34,706	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:42:34,706	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:42:34,706	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:42:35,168	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:42:35,342	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:42:35,342	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:42:37,432	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:42:37,433	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:42:37,433	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:42:37,847	[INFO]	(gateway.py:169)ws_resume	[botpy] 重连启动...
2023-06-30 00:42:37,979	[INFO]	(gateway.py:85)on_message	[botpy] 机器人重连成功! 
2023-06-30 00:42:37,979	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:42:39,805	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:d753d64b9dce6f9176d4a4cfa807b43d
2023-06-30 00:43:05,034	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:617c4270955f6df3cf38e7f64dc5e8d6
2023-06-30 00:46:46,841	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:46:47,815	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:46:47,816	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:46:47,816	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:46:47,816	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:46:48,192	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:46:48,382	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:46:48,382	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:47:44,017	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/members/13564051022262235489/mute, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:086c25df4684d6ff10718b573d0ccfa1
2023-06-30 00:49:35,416	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:49:36,492	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:49:36,492	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:49:36,493	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:49:36,493	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:49:36,813	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:49:36,961	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:49:36,961	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:50:04,511	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/members/13564051022262235489, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:656a7545d1aa305039aa97bf6f0ed837
2023-06-30 00:50:18,158	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:50:19,142	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:50:19,143	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:50:19,143	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:50:19,143	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:50:19,572	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:50:19,716	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:50:19,716	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:50:28,634	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:f52b886f5f60c6eee54171f51ac94615
2023-06-30 00:50:56,110	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:50:57,099	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:50:57,099	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:50:57,100	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:50:57,100	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:50:57,539	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:50:57,644	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:50:57,645	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:51:13,434	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:51:14,418	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:51:14,419	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:51:14,419	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:51:14,419	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:51:14,807	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:51:14,932	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:51:14,933	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:51:22,720	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:2b6f954d1c32bc8ea41b23cf033a2de9
2023-06-30 00:52:31,135	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:52:32,117	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:52:32,117	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:52:32,118	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:52:32,118	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:52:32,574	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:52:32,756	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:52:32,756	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:52:58,295	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/13346486689812486705/members/%7B'id':%20'9282202926517215240',%20'username':%20'%E6%B0%A7%E5%8C%96%E6%88%90%E7%A1%AB',%20'bot':%20False,%20'avatar':%20'http://thirdqq.qlogo.cn/g?b=oidb&k=SZO8VIpuDNNvDpt8y43hzA&kti=ZJ1iMQAAAAA&s=0&t=1676469450'%7D, 错误代码: 404, 返回内容: {'message': '404: Not Found', 'code': 0}, trace_id:49c65e304a0d25f46bca4b9428faf407
2023-06-30 00:52:58,963	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:dc5ab9d6e33092885532be956ffd07a7
2023-06-30 00:54:52,789	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:54:53,811	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:54:53,811	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:54:53,811	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:54:53,811	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:54:54,204	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:54:54,351	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:54:54,352	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:55:04,582	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:186af6fd544dccec0586c420a31e39de
2023-06-30 00:55:05,061	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/13346486689812486705/members/%7B'id':%20'9282202926517215240',%20'username':%20'%E6%B0%A7%E5%8C%96%E6%88%90%E7%A1%AB',%20'bot':%20False,%20'avatar':%20'http://thirdqq.qlogo.cn/g?b=oidb&k=SZO8VIpuDNNvDpt8y43hzA&kti=ZJ1iMQAAAAA&s=0&t=1676469450'%7D, 错误代码: 404, 返回内容: {'message': '404: Not Found', 'code': 0}, trace_id:f9fb45aabb53f9abd5bf3bc34720b177
2023-06-30 00:55:33,306	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:55:34,231	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:55:34,232	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:55:34,232	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:55:34,232	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:55:34,641	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:55:34,811	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「test-测试中」启动成功！
2023-06-30 00:55:34,811	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:55:41,757	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/559842561/messages, 错误代码: 500, 返回内容: {'code': 304022, 'message': 'push time out of range'}, trace_id:e39193d8119ee0f3d2b67461d2356948
2023-06-30 00:56:45,583	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:56:46,609	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:56:46,609	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:56:46,609	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:56:46,609	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:56:47,028	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:56:47,213	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:56:47,213	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:57:52,136	[INFO]	(client.py:159)_bot_login	[botpy] 登录机器人账号中...
2023-06-30 00:57:53,186	[INFO]	(client.py:178)_bot_init	[botpy] 程序启动...
2023-06-30 00:57:53,186	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 00:57:53,187	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 00:57:53,187	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 00:57:53,616	[INFO]	(gateway.py:136)ws_identify	[botpy] 鉴权中...
2023-06-30 00:57:53,760	[INFO]	(gateway.py:80)on_message	[botpy] 机器人「Ower-测试中」启动成功！
2023-06-30 00:57:53,760	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 00:58:22,644	[ERROR]	(http.py:73)_handle_response	[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/guilds/12536101201533055903/members/17933814376511746278, 错误代码: 401, 返回内容: {'message': 'check guild auth not pass', 'code': 11264}, trace_id:15b45030f03e98e7660c214a974fcd1d
2023-06-30 01:07:27,738	[INFO]	(gateway.py:54)on_closed	[botpy] 关闭, 返回码: WSCloseCode.ABNORMAL_CLOSURE, 返回信息: None
2023-06-30 01:07:32,747	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 01:07:32,747	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 01:07:32,747	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 01:07:33,087	[INFO]	(gateway.py:169)ws_resume	[botpy] 重连启动...
2023-06-30 01:07:33,189	[INFO]	(gateway.py:85)on_message	[botpy] 机器人重连成功! 
2023-06-30 01:07:33,189	[INFO]	(gateway.py:217)_send_heart	[botpy] 心跳维持启动...
2023-06-30 01:14:22,569	[INFO]	(gateway.py:54)on_closed	[botpy] 关闭, 返回码: WSCloseCode.ABNORMAL_CLOSURE, 返回信息: None
2023-06-30 01:14:27,571	[INFO]	(connection.py:59)multi_run	[botpy] 最大并发连接数: 1, 启动会话数: 1
2023-06-30 01:14:27,571	[INFO]	(client.py:236)bot_connect	[botpy] 会话启动中...
2023-06-30 01:14:27,571	[INFO]	(gateway.py:110)ws_connect	[botpy] 启动中...
2023-06-30 01:14:27,576	[ERROR]	(gateway.py:50)on_error	[botpy] websocket连接: None, 异常信息 : Cannot connect to host api.sgroup.qq.com:443 ssl:default [getaddrinfo failed]
